### PR TITLE
Fix redirect with urlrewrite setup

### PR DESCRIPTION
**Pull request by Guria**
Redirect must be relative to support running with url rewrite rules

### CODE REVIEW

**Comment by mnaberez** [comment]
Thanks for the pull request but I have decided not to merge it at this time.  As far as I can tell, we've never advertised that the web interface will work in a URL rewrite setup.  I'd rather not make this change because once we say we support it, we can't easily take that away.  The web interface could use some improvement, but supporting it on any arbitrary URL will make that development more difficult.

**Comment by Guria** [comment]
It is not about url rewrite support. Not all environments provide ability to run any tools on any port you want (NAT). So there is only 2 options to use web-uis for tools: subdomains (I'm afraid not supported in such environments as well) and placing them on "subfolder" of main site. You should not expect that web-ui always placed under the root of site.

**Comment by mnaberez** [comment]
> It is not about url rewrite support.

Sorry I was confused by both the title and description of the patch then.

**Comment by Guria** [comment]
Url rewrite is just technic used to place one web-app in sub-path of domain. Sorry, I had to provide more detailed explanation in PR.

**Comment by mnaberez** [comment]
There's now two proposed solutions (#28, this one).  I've reopened #29.

**Pull request closed without merging**
