### PR TITLE
add rlimit configuration for programs

### PR DESCRIPTION
**Pull request by davidbirdsong**
Hi, I've used a hacked up supervisord for years with the options:

``` ini
[program:prog1]
command=/bin/cat
minprocs=4096
minfds=4096
stacksize=10240
```

Which directs supervisor to call setrlimit to the values just after forking to launch the program. For RLIMITS with a soft and hard limit, I've just forced the 'min' value to both since most programs under supervisord are not equipped to call setrlimit on their own behalf.

I think this is generally useful, and I'd love to stop having to manually patch to get updates. 

I ran all tests and had to run tests with root privileges to get the final tests to pas.

Let me know if I've abused any code or if any code style is not good.

### CODE REVIEW

**Comment by ayashjorden** [comment]
Hi all,
Any update when this PR is going to be merged?
Setting the nofiles limit is really important for high-throughput processes.

Thanks,
Yarden

**Comment by Fizzadar** [comment]
I'm assuming this is never going to be merged? Would be nice to know for sure. Moving to either circus or runit in the meantime...

**Comment by mpictor** [comment]
If I understand correctly, the implementation of supervisor is such that a process can be started as a non-root user, **with more privileges than that user is allowed** - bypassing pam, limits.conf, etc. If so, this is an _insane_ design and I'll be advising my company to run the hell away.

Even if this particular problem is fixed, I'll have second thoughts about using supervisor: developers who do not understand security or don't take it seriously are likely to continue creating security problems.

**Comment by woosley** [comment]
I need this feature badly also, maybe time to take a look at circus?

**Comment by antgel** [comment]
We moved to circus, which has it's own "idiosyncrasies". Now looking at systemd. :)

**Comment by carun** [comment]
After 4 years, will this PR be merged?

**Comment by sar009** [comment]
WTF are people at supervisor even listening. It is end of 2019 and still no resolution for a critical request.

**Comment by davidbirdsong** [comment]
> After 4 years, will this PR be merged?

I opened this PR 6 1/2 years ago, but at this point let's all stop bagging on this project and complaining about this PR.  Many suitable alternative projects with active owners have emerged since.

**Pull request closed without merging**
