### PR TITLE
Better syslog configuration and output

### PR DESCRIPTION
**Pull request by samv**
Hi there, thanks for the recent rework in the syslog support.  This is a set of changes which make the syslog output a bit better, reaching this:

```
    Sep 19 10:18:46.285916 Herman daemon.notice supervisord[5296]: supervisord started with pid 5296
    Sep 19 10:18:47.288994 Herman daemon.notice supervisord[5296]: spawned: 'vmstat' with pid 5299
    Sep 19 10:18:47.291366 Herman daemon.notice supervisord[5296]: spawned: 'badvmstat' with pid 5300
    Sep 19 10:18:47.297447 Herman   user.info   vmstat: procs -----------memory---------- ---swap-- -----io---- -system-- ----cpu----
    Sep 19 10:18:47.298812 Herman   user.info   vmstat:  r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa
    Sep 19 10:18:47.299112 Herman   user.info   vmstat:  3  0      0 4874284 244368 1695416    0    0    63    20   62  191  1  0 98  1
    Sep 19 10:18:47.299428 Herman   user.notice badvmstat: vmstat: failed to parse argument: '5;'
    Sep 19 10:18:47.299866 Herman daemon.notice supervisord[5296]: exited: badvmstat (exit status 1; not expected)
    Sep 19 10:18:48.298243 Herman   user.info   vmstat:  0  0      0 4863852 244368 1702904    0    0     0     0 1437 8074  4  3 93  0
    Sep 19 10:18:48.298447 Herman daemon.notice supervisord[5296]: success: vmstat entered RUNNING state, process has stayed up for > than 1 seconds (startse
    Sep 19 10:18:49.298594 Herman   user.info   vmstat:  0  0      0 4863528 244368 1703152    0    0     0     0  737 1475  1  1 99  0
      ...
    Sep 19 10:19:13.488894 Herman daemon.warning supervisord[5296]: received SIGINT indicating exit request
```

Along the lines of the new "stdout_syslog" and "stderr_syslog" boolean values, I have created a new "syslog" top-level configuration, which is configured identically.  Additionally, there are now reasonable defaults for syslog facility and priority (shown in the above, but not logged by default by eg rsyslog).  Finally, if you care, you can select the syslog channel (192 to choose from!) yourself for each stream by putting the channel there instead of "true" in any of the `*syslog` config settings.

Closes issue #162

### CODE REVIEW

**Comment by atombender** [comment]
+1. Can we get this merged?

**Comment by jaraco** [comment]
I raised some issues above, which have gone unaddressed. If it is merged as-is, it would cause us issues and may not be usable in our case.

**Comment by atombender** [comment]
Perhaps @samv could address those issues.

I'm finding the lack of syslog support to be a very sore point. We standardize all our logging around syslog, and wrapping the command in a pipe to `logger` is not a great solution.

**Comment by samv** [comment]
I've rebased and addressed most of the comments on the PR: I've split out the refactor to fix 'syslog' into its own commit (b7abc01).  This series still adds 'stdout:' prefixes for a commit or two and then drops them once support for specifying the syslog priority is there.  That's the way I built this as a progressive series, that is correct at each commit.

The process name is in the appropriate syslog field instead of being in-band in this series, I think that is correct behavior: every syslog program I've used from SunOS 4 to today has supported emitting this to the logfile.  It's the protocol-aware way to do this.

Sorry I didn't get to the other comments, but I did make sure it passes the Python 3 tests :-)

**Comment by honzik666** [comment]
Can you merge samv's changes upstream? The syslog tags containing program name are really nice feature.

**Comment by jsafoodpanda** [comment]
+1 Really looking forward for this feature

**Comment by jaraco** [comment]
I appreciate samv's additional review of the issues I raised. While I retain some trepidation about the acceptance of this PR, its benefits are clear, so I propose to accept the PR and to move forward.

**Comment by sukrit007** [comment]
Would we be able to specify syslog tag to use ?  
```
syslog_tag="myprogram"
```
Appreciate the efforts for this PR.

**Comment by miklos-martin** [comment]
:+1:

**Comment by mnaberez** [comment]
Note for review: [comparison of the various syslog patches](https://github.com/Supervisor/supervisor/pull/162#issuecomment-150986942)

**Comment by mafrosis** [comment]
👍  for improving syslog support

**Comment by boblozano** [comment]
Spent half the morning catching up on history of efforts to improve supervisor syslog support, and this still seems like the most comprehensive. Of course I could be missing something entirely.

Is this going to be merged? If not, is there another plan, or should folks just plan to run their own forks, or perhaps one of the other less than happy workarounds?

Thanks.

**Comment by vlad-tuznichenko** [comment]
Will it ever come be merged? Based on the history it's time to look for another demon(

**Comment by maralla** [comment]
Extremely hope this will be merged!!

**Comment by elijahchancey** [comment]
Please merge this!

**Comment by iredmail** [comment]
Please merge this. Setting syslog facility is useful.
Cannot believe this PR is 7 years old now.

**Comment by samv** [comment]
I am no longer a representative user of this change - most systems I've worked on these days use systemd, kubelet etc that use stdout.  So I'm going to close it; if someone else wants this, they can negotiate its inclusion and/or rebase it themselves.

**Pull request closed without merging**
