### PR TITLE
fix #85 Supervisorctl tail fails on logs with ANSI codes

### LINKED ISSUE #85: Supervisorctl tail fails on logs with ANSI codes
logfile:
^[[31m^[[7memergency^[[0m: Master DOWN!

error: <class 'xml.parsers.expat.ExpatError'>, not well-formed (invalid token): line 51, column 39: file: /usr/lib/python2.6/xmlrpclib.py line: 601

### PR DESCRIPTION
**Pull request by timotheecour**
/cc @@mnaberez 
* fixes https://github.com/Supervisor/supervisor/issues/1293
* fixes https://github.com/Supervisor/supervisor/issues/85

this makes tail work robustly even in presence of binary non ascii data eg ansi color escape codes

EDIT

https://github.com/Supervisor/supervisor/pull/1307 actually also fixes https://github.com/Supervisor/supervisor/issues/1293 https://github.com/Supervisor/supervisor/issues/85
 via a more general solution that better interoperates with command line tools, so maybe this PR isn't essential after https://github.com/Supervisor/supervisor/pull/1307 gets merged

### CODE REVIEW

**Comment by mnaberez** [comment]
We can't just change the API like this because it would break all existing clients.

**Comment by aendeavor** [comment]
> We can't just change the API like this because it would break all existing clients.

All existing clients are already broken, see https://github.com/docker-mailserver/docker-mailserver/issues/1768.

**Comment by mnaberez** [comment]
> All existing clients are already broken, see docker-mailserver/docker-mailserver#1768.

I read the linked ticket and my understanding is the problem reading the log fails when it contains escape sequences, which we are tracking in #85.  

This pull request would have changed the API in an incompatible way, breaking it for all clients regardless of the log content.  In addition to `supervisorctl`, there are also a lot of third party tools that use the API directly, so I don't think we can accept a solution which breaks all of them.

**Comment by aendeavor** [comment]
> > All existing clients are already broken, see docker-mailserver/docker-mailserver#1768.
> 
> 
> 
> I read the linked ticket and my understanding is the problem reading the log fails when it contains escape sequences, which we are tracking in #85.  
> 
> 
> 
> This pull request would have changed the API in an incompatible way, breaking it for all clients regardless of the log content.  In addition to `supervisorctl`, there are also a lot of third party tools that use the API directly, so I don't think we can accept a solution which breaks all of them.

I agree on this.

But this issue exists for 8 years now - can there really nothing be done?

**Pull request closed without merging**
