### PR TITLE
Alternative approach to addressing #1282

### PR DESCRIPTION
**Pull request by vsajip**
All tests passing on Python2 and Python3.

### CODE REVIEW

**Comment by vsajip** [comment]
This should address #1282 - perhaps the reporter can confirm this?

**Comment by vsajip** [comment]
Hmmm - not sure yet about why the Travis jobs failed. Ran fine locally with `tox`.

**Comment by vaclavbartos** [comment]
I had the same problem as discussed in #1282, #1283 and I can confirm this fix works well.

**Comment by vsajip** [comment]
@mnaberez do you need more feedback from others before merging this? Both the OP of #1282 (@Joppie) and @vaclavbartos have indicated that this change worked for them.

**Comment by mnaberez** [comment]
> do you need more feedback from others before merging this? 

Nope, I'm going to run it locally and then merge it.  Thank you!

**Comment by mnaberez** [comment]
I tested this on both Python 2 and 3 using the [reproduce instructions](https://github.com/Supervisor/supervisor/issues/1282#issuecomment-544170227) and it worked on both.  The exception does not occur and the message is logged to syslog.  Merging.

**Pull request merged**
