### PR TITLE
Support forwarding stdout of processes to supervisor stdout

### PR DESCRIPTION
**Pull request by wmanley**
This supports a common container use-case where supervisor is pid 1 in a
container and the container manager will be collecting and recording the
output of supervisor.  Users can now specify:

    stdout_logfile=stdout
    stderr_logfile=stderr

and supervisor will pass any messages logged strieght through.

### CODE REVIEW

**Comment by mnaberez** [comment]
It's pretty easy to achieve this without modifying `supervisord`, and the usage is almost the same:
http://veithen.github.io/2015/01/08/supervisord-redirecting-stdout.html

There's also a plugin:
https://github.com/coderanger/supervisor-stdout

**Comment by wmanley** [comment]
> It's pretty easy to achieve this without modifying supervisord, and the usage is almost the same:
http://veithen.github.io/2015/01/08/supervisord-redirecting-stdout.html

Previously I had been using this workaround, but it doesn't work when you don't have permission to open `/dev/stdout`.  This is the case with containers started with `systemd-nspawn`.  This is why I created this patch.

**Comment by mnaberez** [comment]
> Previously I had been using this workaround, but it doesn't work when you don't have permission to open /dev/stdout. This is the case with containers started with systemd-nspawn. This is why I created this patch.

The plugin linked above won't have that problem.

**Comment by flavius** [comment]
@mnaberez The plugin doesn't seem to work any more.

**Comment by mnaberez** [comment]
> The plugin doesn't seem to work any more.

Please report issues with the plugin on [its issue tracker](https://github.com/coderanger/supervisor-stdout).

**Pull request closed without merging**
