### PR TITLE
Add changelog URL to package metadata

### PR DESCRIPTION
**Pull request by intgr**
When [Renovate bot](https://docs.renovatebot.com/) creates an automated pull request to update supervisord, it can automatically include the link to changelog so it's easier to find out what changed.

The URL name has to be one of: 'changelog', 'change log', 'changes', 'release notes', 'news', "what's new" (case insensitive). Source: https://github.com/renovatebot/renovate/blob/c3a87b687ed44a1a100e0e4f91b81e22b7c32482/lib/modules/datasource/pypi/index.ts#L130-L140

### CODE REVIEW

**Comment by mnaberez** [comment]
> When [Renovate bot](https://docs.renovatebot.com/) creates an automated pull request to update supervisord, it can automatically include the link to changelog so it's easier to find out what changed.

Please do not use bots or submit automated pull requests to this project.

**Comment by intgr** [comment]
No, you misunderstood.

This PR was not opened using a bot. This PR was created manually.

The *reason* for submitting this PR is that I am using Renovate bot in a 3rd project, where I also use supervisord. Whenever there is an update, Renovate can directly link to supervisord's changelog, so I don't have to manually search the web to figure out what changed between the versions.

**Comment by mnaberez** [comment]
Supervisor publishes the changelog at these places:
- Directly on the PyPI release page (https://pypi.org/project/supervisor/
- In a `CHANGES.txt` file in the root of the repository (https://github.com/Supervisor/supervisor)
- Linked from the sidebar on the first page of website (http://supervisord.org)

The changelog is also the first hit for "supervisor changelog" on google, bing, and duckduckgo.  

I don't think the changelog is difficult to find, so I'd rather not modify `setup.py` to support this bot.  Everything we add to `setup.py` increases maintenance burden and the possibility that install fails for some reason.  I'd prefer to keep `setup.py` reduced to only what is absolutely necessary for installation.

**Comment by mnaberez** [comment]
Unrelated to any third party bots, PyPI also displays `project_urls` under "Project Links" in the sidebar, which may be helpful to users.  I'll merge this so the link is shown on PyPI.

Bildschirm­foto 2022-12-27 um 10 31 50 AM

**Comment by intgr** [comment]
Thanks :+1:

**Pull request merged**
