### PR TITLE
Don't recurse when reaping

### PR DESCRIPTION
**Pull request by aidanhs**
Stumbled across this code, thought it could be simplified.

Removes an unnecessary test as well.

### CODE REVIEW

**Comment by mnaberez** [comment]
Thanks, but I don't see any reason to change this.

**Comment by aidanhs** [comment]
I found the code confusing when I initially came across it. This change seemed like a decent clarity improvement (fewer function arguments, fewer lines of code, less complexity to need to test) but it is of course your call.

Have you considered a contribution guide to indicate what kind of thing you're interested in? Something like:

> Pull requests for bug fixes and features are welcome, though significant features should be discussed on the mailing list beforehand.

> General refactoring will not be merged unless there is an extremely compelling reason to do so.

I can make a PR to add this if you agree with the general wording? It'll help prevent wasted time on PRs like this one.

**Comment by mnaberez** [comment]
> General refactoring will not be merged unless there is an extremely compelling reason to do so.

I don't agree with this wording and I also don't see a reason to add such disclaimers.  Many patches are merged including refactoring.  They are reviewed on a case by case as they are submitted.  I understand that you think this is an improvement, I just don't happen to agree with you on this, sorry.

**Comment by aidanhs** [comment]
Fair enough.

**Comment by aidanhs** [comment]
To elaborate a bit more as you gave such a comprehensive response, which I appreciate - you make a very good point regarding external calls which may break, I hadn't thought about that.

I definitely understand the problems of trying to keep backwards compatibility in mature programs, so this is very reasonable.

> I probably should have given you more of a response why, but you didn't offer much with the patch either.

You're right, I apologise for that.

**Comment by mnaberez** [comment]
Thank you for the patch, I do appreciate it, and please feel free to submit more patches in the future.  It's an old program so there's some issues around that but in general we do want to improve it.

**Comment by aidanhs** [comment]
Willdo! :)

**Pull request closed without merging**
