### PR TITLE
Reflect new glibc 2.31 default value for SOMAXCONN on tests (closes: #1346)

### PR DESCRIPTION
**Pull request by samueloph**
closes: #1346

### CODE REVIEW

**Comment by mnaberez** [comment]
Will this change now cause it to fail on older glibc instead?

**Comment by samueloph** [comment]
@mnaberez Yes, it will

**Comment by samueloph** [comment]
hmm, would it be good solution to make the test check to either 128 or 4096?

**Comment by mnaberez** [comment]
Thanks for your help and this patch.  I have just committed 48fd49eb857c2eaf5dcb45ff100d23ca7d41b4e9 which I believe will fix it.  Please test this if you are able and leave a comment on #1346 if it still has issues.

**Pull request closed without merging**
