### PR TITLE
Fix start duplicate supervisord will remove exists pidfile

### LINKED ISSUE #878: Start duplicate supervisord will remove exists pidfile
```shell

$ supervisord --version
3.3.1
$ supervisord --pidfile /tmp/test.pid
$ ls /tmp/test.pid
/tmp/test.pid
$ supervisord --pidfile /tmp/test.pid
Error: Another program is already listening on a port that one of our HTTP servers is configured to use.  Shut this program down first before starting supervisord.
For help, use /usr/local/bin/supervisord -h
$ ls /tmp/test.pid
ls: /tmp/test.pid: No such file or directory
```

### PR DESCRIPTION
**Pull request by coldnight**
This pull request fixes #878.

### CODE REVIEW

**Comment by mnaberez** [comment]
Fixes #613.

Could you please squash these commits?

**Comment by coldnight** [comment]
I will try squash these commits  later.

**Comment by coldnight** [comment]
@mnaberez The CI is failure, but it seems not my fault.

**Comment by coldnight** [comment]
#880 fixes the CI problem.

**Comment by mnaberez** [comment]
CI failure should be fixed since fa7e3f56c8e4fd1e6e19070a0bcffc0bf5ab3192.

**Comment by coldnight** [comment]
@mnaberez please review, thanks.

**Pull request merged**
