### PR TITLE
Add support for Docker within supervisor

### PR DESCRIPTION
**Pull request by maihde**
I like using supervisor to manage my Docker processes, but it doing so has one major downside, there are many situations where a docker container will stop but will not be removed.  When this happens supervisor is unable to restart the process because the container name is already taken (because I prefer to have my container names match the supervisor process names).

These changes allow supervisor to be fully aware of managing Docker containers as part of the regular process management.  I had considered making this a plugin, but the rpcinterface plugin mechanism didn't allow me to easily extend the configuration file syntax for the [program] sections.

The only significant design decision that I made was using subprocess to issue the docker stop/rm commands.  This means that supervisor would require at least Python 2.4.  If that is a problem I can replace it with alternate approaches.

### CODE REVIEW

**Comment by psigen** [comment]
> there are many situations where a docker container will stop but will not be removed.

Just curious, is this case somehow not handled by the docker `--rm` flag?  That's how I have been handling this situation myself and haven't seen any zombie containers.

https://docs.docker.com/engine/reference/run/#clean-up-rm

**Comment by maihde** [comment]
Here are the ones I've encountered:

a) The machine is rebooted
b) The docker daemon is shutdown

Otherwise, I agree with you, the --rm flag would be preferred.

Michael

**Comment by psigen** [comment]
Good point w/ those use cases.

I have been following the trick used by CoreOS `fleet` launch scripts (which use a `supervisor`-link interface) in which the pre-launch command is to remove any existing container:

```ini
[Unit]
Description=MyApp
After=docker.service
Requires=docker.service

[Service]
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill busybox1
ExecStartPre=-/usr/bin/docker rm busybox1
ExecStartPre=/usr/bin/docker pull busybox
ExecStart=/usr/bin/docker run --name busybox1 busybox /bin/sh -c "trap 'exit 0' INT TERM; while true; do echo Hello World; sleep 1; done"
ExecStop=/usr/bin/docker stop busybox1
```
https://coreos.com/fleet/docs/latest/launching-containers-fleet.html

**Comment by maihde** [comment]
Yeah, that would work as well (i.e. having supervisor provide a pre-launch
command).

~Michael

**Comment by vladfr** [comment]
@maihde @psigen what would be the disadvantages of just using the existing "command" arg?
Do you see any benefits of implementing a pre-command?

Should look something like this:
```
docker ps --all --format {{.Names}} | grep ^myContainer$ \
  && docker stop myContainer && docker rm myContainer
docker run --rm --name myContainer my/image
```

My guess is that you'd need to trap & pass TERM, since this would be a bash script starting the `docker` process (as mentioned in #772 and http://veithen.github.io/2014/11/16/sigterm-propagation.html)

**Comment by psigen** [comment]
@vladfr I don't think there is any particular advantage to the pre-launch command here other than it exists in the `fleet` lifecycle already. `fleet` [copies this lifecycle](https://coreos.com/docs/launching-containers/launching/getting-started-with-systemd/#advanced-unit-files) from `systemd`.

However, note that this lifecycle has some advantages w.r.t dependency management that might relate to your work here https://github.com/Supervisor/supervisor/issues/122 (_:+1: thank you for looking into this!_).

There are cases where a failure during `pre-launch` can efficiently _preempt_ the launch of dependent processes. I suspect this is one reason the stage exists in `systemd`: [for its `Before/After/Requires/Wants` dependency semantics](https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files#unit-section-directives) (which are definitely worth studying when dealing with #122).

**Pull request closed without merging**
