### PR TITLE
Make startretries accept -1 in order to never stop retrying

### PR DESCRIPTION
**Pull request by mediocregopher**

### CODE REVIEW

**Comment by kigakree** [comment]
+1

**Comment by mediocregopher** [comment]
To the maintainers: This doesn't currently merge but if anyone could give me some indication if this feature is wanted or not I can either fix it up or close the PR. Until then I'm just going to let it sit and not fuss with it.

**Comment by mnaberez** [comment]
I've never had a process running under `supervisord` that took hundreds or thousands of failed respawns and then successfully started, so I don't really understand the use case for this special `-1` value.  It seems like almost the same thing can be achieved by setting `startretries` to a large number.

**Comment by mediocregopher** [comment]
Alright well thanks for looking at the PR anyway :)

**Comment by gjcarneiro** [comment]
FWIW, I often have programs tha

**Comment by mhf-ir** [comment]
+1

**Comment by triccardi-systran** [comment]
This is a useful feature; setting a large number is just a workaround.

**Pull request closed without merging**
