### PR TITLE
Add two configuration properties to the getAllConfigInfo method

### PR DESCRIPTION
**Pull request by yellmean**
Add two configuration properties to the getAllConfigInfo method

### CODE REVIEW

**Comment by mnaberez** [comment]
> Add two configuration properties to the getAllConfigInfo method

Why are you requesting this change?

**Comment by yellmean** [comment]
> > Add two configuration properties to the getAllConfigInfo method
> 
> Why are you requesting this change?

In order to facilitate the detection and management of the program, this time I just want to use these two properties, more importantly, you can more fully expose the relevant configuration information to the interface without the user to do more work.

**Review by mnaberez — CHANGES_REQUESTED** [review]
Needs tests

**Comment by mnaberez** [comment]
> In order to facilitate the detection and management of the program, this time I just want to use these two properties, more importantly, you can more fully expose the relevant configuration information to the interface without the user to do more work.

I am having difficulty following this.  Maybe you could explain the actual task you tried to do that required you to add these?  Thank you.

**Pull request merged**
