### PR TITLE
Python3 syslog fix

### PR DESCRIPTION
**Pull request by Joppie**

### CODE REVIEW

**Comment by Joppie** [comment]
This pull request addresses issue #1283

**Comment by Joppie** [comment]
It appears the `SyslogHandlerTests` test class is meant to verify that both ascii and unicode strings are handeled correctly. However, in `test_emit_ascii_noerror` the expression `'hello'` is used, which is not a `bytes` (ascii) type under python3. Using the expression `b'hello'` will ensure that this is an ascii string under both python2.7 and python3. Making this change will cause the test to fail under python3.

**Comment by Joppie** [comment]
I'm not sold that this is the correct way to address this problem, but I thought I'd go ahead and show a potential solution. One thing of note, because the `fmt` string is in the base `Logger` class is `'%(message)s', this means the the output messages will always be unicode strings under python3. Under python2, they will be ascii strings when the input messages is ascii, and unicode strings when the input mesage is unicode. I'm not sure what the desired behavior should be.

**Comment by mnaberez** [comment]
cc: @vsajip

**Comment by vsajip** [comment]
Actually, the issue addressed appears ro be #1282

**Comment by vsajip** [comment]
See also #1284 for the alternative approach I suggested.

**Comment by Joppie** [comment]
I was unsure of the desired behavior for when messages, formats, etc should be ascii/byte strings or Unicode strings in both python2 and python3. This pull request was mainly to provide some context for issue #1282. #1284 seems like a better fix, so I'm closing this request.

**Comment by vsajip** [comment]
Generally, I believe messages, formats etc. should logically be Unicode (`unicode` on Python 2 and `str` on Python 3), as they are meant to be text for human consumption. Generally, `bytes` should only be used when communicating between processes or when doing I/O (file, socket). This "purist" approach sometimes has to be modified for reasons of legacy code.

**Comment by vsajip** [comment]
Just to confirm - did you try the #1284 fix in your environment? Did messages show up in syslog with that fix applied?

**Comment by Joppie** [comment]
I just tested it and it does fix the issue in the environment I am using. Thanks.

**Pull request closed without merging**
