### PR TITLE
Fix remaining Python 3 compatibility issues

### LINKED ISSUE #565: tail -f exits immediately on python3
If I do something like:

```
supervisorctl tail -f etl_process_updates_worker
```

It'll grab the first line of output and then exit

### LINKED ISSUE #638: unicode decoding error while reading from stderr / stdout
Having a supervisor configuration that produces non-utf-8 data (e.g. binary) triggers an error in supervisor followed by a close of stdout / stderr for that process. This leads to a not responding process because data which should be send to stdout / stderr are blocked / stuck in the write operation.

```
[program:produce-unicode-error]
command=echo -e "\x88"
```

Log message of supervisor (formatted):

```
2015-07-21 15:56:04,934 CRIT uncaptured python exception, closing channel <POutputDispatcher at 26310992 for <Subprocess at 26313168 with name produce-unicode-error in state STARTING>  
    (stdout)> (<type 'exceptions.UnicodeDecodeError'>:'utf8' codec can't decode byte 0x88 in position 0: invalid start byte
    [/opt/python2.6/supervisor/supervisord.py|runforever|223] 
    [/opt/python2.6/supervisor/dispatchers.py|handle_read_event|260] 
    [/opt/python2.6/supervisor/options.py|readfd|1507]
    [/opt/python2.6/supervisor/compat.py|as_string|24]
    [/opt/python2.6/encodings/utf_8.py|decode|16])
2015-07-21 15:56:04,934 DEBG fd 6 closed, stopped monitoring <POutputDispatcher at 26310992 for <Subprocess at 26313168 with name produce-unicode-error in state STARTING> (stdout)>
```

### LINKED ISSUE #663: Event listeners crash supervisord on Python 3
I get the following error when running the master with Python 3.2:

```
 File "/opt/ls/lx/env/d/python32/supervisor/process.py", line 825, in dispatch
    ok = self._dispatchEvent(event)
  File "/opt/ls/lx/env/d/python32/supervisor/process.py", line 873, in _dispatchEvent
    process.write(as_bytes(envelope))
  File "/opt/ls/lx/env/d/python32/supervisor/process.py", line 100, in write
    dispatcher.input_buffer += chars
TypeError: Can't convert 'bytes' object to str implicitly
```

When I do replace in process.py (line 873) `as_bytes` by `as_string`, then it is working...

### LINKED ISSUE #664: Py3k - error in xmlrpc API if non-ascii-bytes are transmitted
The XMLRPC interface seems not being able to transmit non-ascii bytes.
If I have for example a `process_name` like this `"test_öäü"`, then everything is working (the process is started by the supervisor)  but the XMLRPC-method `getAllProcessInfo` is not usable any more because an exception is raise:`xml.parsers.expat.ExpatError: unclosed token: line 67, column 0`

It seems, that XMLRPC-XML-response has been cut at the end.
When making an xmlrpc-call in verbose-mode, then I can see this:

```
send: b"POST /RPC2 HTTP/1.1\r\nHost: lsdev01:9101\r\nAuthorization: Basic c3VwZXJ2aXNvcnVzZXI6JDNjdXIzJHVwM3J2aSRvcg==\r\nAccept-Encoding: gzip\r\nContent-Type: text/xml\r\nUser-Agent: xmlrpclib.py/1.0.1 (by www.pythonware.com)\r\nContent-Length: 175\r\n\r\n<?xml version='1.0'?>\n<methodCall>\n<methodName>supervisor.getAllProcessInfo</methodName>\n<params>\n<param>\n<value><boolean>1</boolean></value>\n</param>\n</params>\n</methodCall>\n"
reply: 'HTTP/1.1 200 OK\r\n'
header: Date header: Content-Length header: Content-Type header: Server body: b"<?xml version='1.0'?>\n<methodResponse>\n<params>\n<param>\n<value><array><data>\n<value><struct>\n<member>\n<name>description</name>\n<value><string></string></value>\n</member>\n<member>\n<name>pid</name>\n<value><int>20134</int></value>\n</member>\n<member>\n<name>stderr_logfile</name>\n<value><string></string></value>\n</member>\n<member>\n<name>stop</name>\n<value><int>0</int></value>\n</member>\n<member>\n<name>logfile</name>\n<value><string>/opt/ls/lx/log/test.out</string></value>\n</member>\n<member>\n<name>exitstatus</name>\n<value><int>0</int></value>\n</member>\n<member>\n<name>spawnerr</name>\n<value><string></string></value>\n</member>\n<member>\n<name>now</name>\n<value><int>1444120850</int></value>\n</member>\n<member>\n<name>group</name>\n<value><string>test</string></value>\n</member>\n<member>\n<name>name</name>\n<value><string>test_\xc3\xb6\xc3\xa4\xc3\xbc</string></value>\n</member>\n<member>\n<name>statename</name>\n<value><string>STARTING</string></value>\n</member>\n<member>\n<name>start</name>\n<value><int>1444120850</int></value>\n</member>\n<member>\n<nam"
body: b'e>state</name>\n<value><int>10</int></value>\n</member>\n<member>\n<name>stdout_logfile</name>\n<value><string>/opt/ls/lx/log/test.out</string></value>\n</member>\n</struct></value>\n</data></array></value>\n</param>\n</params>\n</methodRespons'
```

Here we can see clearly that the last three bytes are omitted. (`'e>\n'`)

I don't know if the same problem van be observed for python 2...

### LINKED ISSUE #835: sendProcessStdin() always raises INCORRECT_PARAMETERS on Python 3
Start `supervisord` in the foreground with a subprocess running:

```
$ python --version
Python 3.5.2

$ cat supervisord.conf
[supervisord]
loglevel = blather
nodaemon = true

[inet_http_server]
port = 127.0.0.1:9001

[supervisorctl]
serverurl = http://127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:cat]
command = /bin/cat

$ supervisord -c supervisord.conf
```

In another terminal, try the XML-RPC method `sendProcessStdin`:

```
$ python
Python 3.5.2 (default, Sep 10 2016, 08:21:44)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from xmlrpc.client import ServerProxy
>>> server = ServerProxy('http://127.0.0.1:9001/RPC2', verbose=True)
>>> server.supervisor.sendProcessStdin('cat', 'hello')
send: b'POST /RPC2 HTTP/1.1\r\nHost: 127.0.0.1:9001\r\nAccept-Encoding: gzip\r\nContent-Type: text/xml\r\nUser-Agent: Python-xmlrpc/3.5\r\nContent-Length: 229\r\n\r\n'
send: b"<?xml version='1.0'?>\n<methodCall>\n<methodName>supervisor.sendProcessStdin</methodName>\n<params>\n<param>\n<value><string>cat</string></value>\n</param>\n<param>\n<value><string>hello</string></value>\n</param>\n</params>\n</methodCall>\n"
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type header: Content-Length header: Date header: Server body: b"<?xml version='1.0'?>\n<methodResponse>\n<fault>\n<value><struct>\n<member>\n<name>faultString</name>\n<value><string>INCORRECT_PARAMETERS</string></value>\n</member>\n<member>\n<name>faultCode</name>\n<value><int>2</int></value>\n</member>\n</struct></value>\n</fault>\n</methodResponse>\n"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1150, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1322, in parse_response
    return u.close()
  File "/usr/lib/python3.5/xmlrpc/client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 2: 'INCORRECT_PARAMETERS'>
```

`supervisord` log output:

```
2016-10-09 10:09:10,394 TRAC 127.0.0.1:Medusa (V1.12) started at Sun Oct  9 10:09:10 2016
    Hostname: localhost
    Port:9001
2016-10-09 10:09:10,400 INFO RPC interface 'supervisor' initialized
2016-10-09 10:09:10,400 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2016-10-09 10:09:10,401 INFO supervisord started with pid 10016
2016-10-09 10:09:11,404 INFO spawned: 'cat' with pid 10019
2016-10-09 10:09:12,408 INFO success: cat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-10-09 10:09:13,773 BLAT read event caused by <supervisor.http.supervisor_af_inet_http_server listening 127.0.0.1:9001 at 0x7f8684bf2128>
2016-10-09 10:09:13,774 BLAT read event caused by <supervisor.http.deferring_http_channel connected 127.0.0.1:37458 at 0x7f8684baf198 channel#: 0 requests:0>
2016-10-09 10:09:13,775 TRAC XML-RPC method called: supervisor.sendProcessStdin()
2016-10-09 10:09:13,775 TRAC XML-RPC method supervisor.sendProcessStdin() returned fault: [2] INCORRECT_PARAMETERS
2016-10-09 10:09:13,775 TRAC 127.0.0.1:37458 - - [09/Oct/2016:17:09:13 -0800] "POST /RPC2 HTTP/1.1" 200 397
2016-10-09 10:09:13,776 BLAT write event caused by <supervisor.http.deferring_http_channel connected 127.0.0.1:37458 at 0x7f8684baf198 channel#: 0 requests:1>
```

Tested on e73d0174339d182ead9c7b26a7c9dae9649f8b00.  The `INCORRECT_PARAMETERS` fault comes from the [`traverse` function in `xmlrpc.py`](https://github.com/Supervisor/supervisor/blob/e73d0174339d182ead9c7b26a7c9dae9649f8b00/supervisor/xmlrpc.py#L459-L462) catching a `TypeError`.  It is the same exception seen https://github.com/Supervisor/supervisor/issues/663#issuecomment-252465751.  Once that is fixed, we should try the above again to be sure `sendProcessStdin` is also fixed.

### LINKED ISSUE #836: supervisorctl fg always raises INCORRECT_PARAMETERS on Python 3
Start `supervisord` in the foreground with a subprocess running:

```
$ python --version
Python 3.5.2

$ cat supervisord.conf
[supervisord]
loglevel = blather
nodaemon = true

[inet_http_server]
port = 127.0.0.1:9001

[supervisorctl]
serverurl = http://127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:cat]
command = /bin/cat

$ supervisord -c supervisord.conf
```

In another terminal, start `supervisorctl fg` and type something followed by return:

```
$ supervisorctl -c supervisord.conf fg cat
==> Press Ctrl-C to exit <==
hi
ERROR: <Fault 2: 'INCORRECT_PARAMETERS'>
Exiting foreground
$
```

Tested on 427eb2bc6b08f788573deb91d1391d93f8b58a1b.  Note that in earlier versions, `fg` swallowed most XML-RPC faults so it would fail silently.  The cause of `INCORRECT_PARAMETERS` is the same as https://github.com/Supervisor/supervisor/issues/835#issue-181898879.   Once that is fixed, we should try the above again to be sure `supervisorctl fg` is also fixed.

### PR DESCRIPTION
**Pull request by mnaberez**
This pull request applies a patch submitted by @vsajip that overhauls bytes/strings handling inside `supervisord` to fix all of the open Python 3 issues.  Test cases are included for all of those issues.

Closes #471
Closes #565
Closes #638
Closes #663
Closes #664
Closes #835
Closes #836
Closes #974

Thank you @vsajip!

### CODE REVIEW

**Comment by Lucretiel** [comment]
🥇 🎆 🎉

**Comment by ciarancourtney** [comment]
7da10a884671060d156186f2cd276ecb855b3179 seems good to me during quick testing on python3.6, when can we expect the 4.0 release?

**Comment by zjjott** [comment]
nice!

**Comment by cclauss** [comment]
Just this repo, httplib2, and the Mozilla build tools left on https://python3wos.appspot.com

**Comment by ibnbay00** [comment]
When version 4 is release or version to support python 3...? 👍

**Comment by waldyrious** [comment]
> Just this repo, httplib2, and the Mozilla build tools left on python3wos.appspot.com

FYI, httplib2 is no longer there since v0.11.0 (released 2 days ago): https://github.com/httplib2/httplib2/issues/50#issuecomment-375046128

**Pull request merged**
