### PR TITLE
Describe how to restart multiple processes at once

### PR DESCRIPTION
**Pull request by eoghanmurray**

### CODE REVIEW

**Comment by mnaberez** [comment]
Thanks for the pull request, but I'm going to close this because that syntax isn't actually supported by Supervisor.  You can get that syntax (`supervisorctl restart foo_*`) by installing the [supervisor-wildcards](https://github.com/aleszoulek/supervisor-wildcards) plugin.  

You can, however, restart all programs in a group with `supervisorctl restart groupname:` or `supervisorctl restart groupname:*` without installing any plugins.  

We have an open issue (#250) to add supervisorctl docs.  This is something we need to fix.  We will add a new section rather than putting it inline with the config file options.

**Comment by eoghanmurray** [comment]
I don't have supervisor-wildcards installed.  Do you mean that it isn't actually *supposed* to be supported but that it works?

**Comment by mnaberez** [comment]
The syntax documented in this pull request (`restart foo_*`) is not supported and doesn't work.  The syntax to restart all processes in a group is `restart foo:` or `restart foo:*`.

Minimal `supervisord.conf` with a program `foo` that has 5 processes:

    [supervisord]
    logfile = /tmp/supervisord.log
    
    [inet_http_server]
    port = 127.0.0.1:9001
    
    [supervisorctl]
    serverurl = http://127.0.0.1:9001
    
    [rpcinterface:supervisor]
    supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
    
    [program:foo]
    command = /bin/cat
    process_name = foo_%(process_num)s
    numprocs = 5

Start `supervisord` in the forground with that config:

    $ supervisord -n -c /path/to/supervisord.conf

Using the `supervisorctl restart foo_*` syntax in this pull request:

    $ supervisorctl -c supervisord.conf
    foo:foo_0                        RUNNING   pid 1294, uptime 0:00:32
    foo:foo_1                        RUNNING   pid 1295, uptime 0:00:32
    foo:foo_2                        RUNNING   pid 1296, uptime 0:00:32
    foo:foo_3                        RUNNING   pid 1297, uptime 0:00:32
    foo:foo_4                        RUNNING   pid 1298, uptime 0:00:32
    supervisor> restart foo_*
    foo_*: ERROR (no such process)
    foo_*: ERROR (no such process)

Using the supported `group:` or `group:*` syntax:

    $ supervisorctl -c supervisord.conf
    foo:foo_0                        RUNNING   pid 1294, uptime 0:01:22
    foo:foo_1                        RUNNING   pid 1295, uptime 0:01:22
    foo:foo_2                        RUNNING   pid 1296, uptime 0:01:22
    foo:foo_3                        RUNNING   pid 1297, uptime 0:01:22
    foo:foo_4                        RUNNING   pid 1298, uptime 0:01:22
    supervisor> restart foo:
    foo:foo_0: stopped
    foo:foo_1: stopped
    foo:foo_2: stopped
    foo:foo_3: stopped
    foo:foo_4: stopped
    foo:foo_0: started
    foo:foo_1: started
    foo:foo_2: started
    foo:foo_3: started
    foo:foo_4: started
    supervisor> restart foo:*
    foo:foo_0: stopped
    foo:foo_1: stopped
    foo:foo_2: stopped
    foo:foo_3: stopped
    foo:foo_4: stopped
    foo:foo_0: started
    foo:foo_1: started
    foo:foo_2: started
    foo:foo_3: started
    foo:foo_4: started

**Comment by eoghanmurray** [comment]
My bad, don't know what I was thinking with `foo_*`.

**Pull request closed without merging**
